<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Usamos la conexión 'oracle' para crear la tabla users
        Schema::connection('oracle')->create('users', function (Blueprint $table) {
            // Laravel asume que 'id' será NUMBER(10) generado automáticamente
            $table->id();                    // equivale a NUMBER GENERATED BY DEFAULT AS IDENTITY
            $table->string('name');          // VARCHAR2(255) por defecto
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();            // created_at, updated_at => DATE
        });

        Schema::connection('oracle')->create('password_reset_tokens', function (Blueprint $table) {
            $table->string('email')->primary();
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });

        Schema::connection('oracle')->create('sessions', function (Blueprint $table) {
            $table->string('id')->primary();
            $table->foreignId('user_id')->nullable()->index();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->longText('payload');
            $table->integer('last_activity')->index();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection('oracle')->dropIfExists('sessions');
        Schema::connection('oracle')->dropIfExists('password_reset_tokens');
        Schema::connection('oracle')->dropIfExists('users');
    }
};

